### ISSUE TITLE
Overloading functions - causes error

### ISSUE THREAD

**Issue by crazywolf132** [mani-language/Mani#89]
**Describe the bug**

> The overloaded functions don't replace each other if they match. The way they are counted as matching is if the parameter sizes are the same.

**To Reproduce**
Steps to reproduce the behaviour:

> **The best way to see this happening is by using the frame API, and creating a listener on a button**

> 1. Create 2 functions with the same name, same arguments, but different body.
> 2. Create a basic window and a button.
> 3. Add a click listener to it.
> 4. It will complain about a list being provided. This is due to the same function being added twice.

Code to reproduce:
``` JS
    load 'frame';

    let frame = window('Some title');
    let button = windowButton('A super simple button', 0, 0, 100, 100);

    fn test() { say 'wow, first function'; }

    fn test() { say 'wow, second function'; }

    button.listener(test);
```

**Expected behaviour**

> The second function should replace the first one... therefor not being a list. Unless... there is other overridden functions. 

**Error**
If applicable, please provide the full error.

```
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class com.mani.lang.domain.ManiFunction (java.util.ArrayList is in module java.base of loader 'bootstrap'; com.mani.lang.domain.ManiFunction is in unnamed module of loader 'app')
	at com.mani.lang.Modules.frame.frame$CustomMouseListener.mouseClicked(frame.java:374)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4556)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Desktop (please complete the following information):**
>  - OS: [MACOS]
> - Version [CATALINA]

**Standard Library:**
Were you using a standard library?

> - [X] No

If yes, what libraries?
> N/A

If applicable, did you have internet connection?
> - [X] Yes

**Additional context**

**Comment by crazywolf132** [comment]
Another way we could battle this is by complaining about multiple of the same function. Requiring the user to only use a function that has **NOT** been declared more than once.
